name: Deploy to Jamsocket
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Jamsocket
        uses: jamsocket/jamsocket-deploy-action@v0.1.0
        with:
          jamsocket_api_token: ${{ secrets.JAMSOCKET_API_TOKEN }}
          jamsocket_account: my-jamsocket-account
          jamsocket_service: my-jamsocket-service
          docker_build_context: '.'
          dockerfile_path: ./Dockerfile.jamsocket
